export const LOGIN_PAGE = '/login'
export const ADMIN_CATEGORY = '/admin/categories'
export const ADMIN_CATEGORY_PAGE = '/admin/category'
export const ADMIN_PRODUCTS = '/admin/products'
export const ADMIN_PRODUCT = '/admin/product'